### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module NextJs build

### ISSUE THREAD

**Issue by zilkenberg22** [mkhstar/suneditor-react#283]
### version :
  "suneditor": "^2.43.14",
   "suneditor-react": "^3.4.1"

### Main Code :

```
import React from "react";
import dynamic from "next/dynamic";
import "suneditor/dist/css/suneditor.min.css"; // Import Sun Editor's CSS File
import plugins from "suneditor/src/plugins";

const SunEditor = dynamic(() => import("suneditor-react"), { ssr: false });

const MyComponent = (props) => {
    return (
        <div>
            <p> My Other Contents </p>
            <SunEditor
                setOptions={{
                    height: 200,
                    plugins: plugins,
                    buttonList: [
                        ["undo", "redo"],
                        ["bold", "underline", "italic", "strike"],
                        ["fontColor", "hiliteColor", "formatBlock"],
                        ["outdent", "indent", "align", "list", "horizontalRule"],
                        ["link", "image", "video"],
                    ],
                }}
            />
        </div>
    );
};
export default MyComponent;
```

### ERROR:
```
SyntaxError: Cannot use import statement outside a module
import align from './submenu/align';
```

**Comment by mnezmah** [comment]
I have the same issue:
    "suneditor": "^2.38.7",
    "suneditor-react": "^3.4.1",

` .../node_modules/suneditor/src/plugins/index.js:4
    import blockquote from './command/blockquote';
    ^^^^^^

import React from 'react';
import SunEditor from 'suneditor-react';
import 'suneditor/dist/css/suneditor.min.css'; // Import Sun Editor's CSS File

export const Wysiwyg = () => {
    return (
        <div>
            <p> My Other Contents </p>
            <SunEditor />
        </div>
    );
};
    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/suneditor-react/dist/SunEditor.js:42:33)
`

**Comment by shyamal2411** [comment]
```
**// --------- import for dynamic in next js -------------------**
import dynamic from "next/dynamic";

import React from "react";
import "suneditor/dist/css/suneditor.min.css"; // Import Sun Editor's CSS File
import plugins from "suneditor/src/plugins";

**// ------------------- dynamically adding library or module -------------------**
const SunEditor = dynamic(() => import("suneditor-react"), { ssr: false });

const MyComponent = (props) => {
    return (
        <div>
            <p> My Other Contents </p>

**//------------------- using dynamically added library or module -------------------**
            <SunEditor
                setOptions={{
                    height: 200,
                    plugins: plugins,
                    buttonList: [
                        ["undo", "redo"],
                        ["bold", "underline", "italic", "strike"],
                        ["fontColor", "hiliteColor", "formatBlock"],
                        ["outdent", "indent", "align", "list", "horizontalRule"],
                        ["link", "image", "video"],
                    ],
                }}
            />
        </div>
    );
};
export default MyComponent;
```


This code is a React component that imports and uses the Sun Editor library, which is a WYSIWYG editor. Here's an explanation of the code:

- The code imports the necessary dependencies: React, dynamic from Next.js, and the Sun Editor library. Additionally, it imports the CSS file for Sun Editor to apply the default styles.
- The component uses dynamic from Next.js to asynchronously import the Sun Editor component. The ssr: false option ensures that the Sun Editor component is only loaded on the client-side and not during server-side rendering.
- The component MyComponent is exported as the default export, making it available for use in other parts of the application.
